apiVersion: v1
kind: Secret
metadata:
  name: usercredits-secret
  namespace: dr3at
type: Opaque
data:
  # Password: postgres123 (base64 encoded)
  SPRING_R2DBC_PASSWORD: cG9zdGdyZXMxMjM=
  SPRING_FLYWAY_PASSWORD: cG9zdGdyZXMxMjM=
