apiVersion: v1
kind: Service
metadata:
  name: usercredits-service
  namespace: dr3at
spec:
  selector:
    app: usercredits
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: LoadBalancer
