apiVersion: v1
kind: Service
metadata:
  name: library-service
  namespace: dr3at
spec:
  selector:
    app: library
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
